name: Deploy FastAPI App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          # If you have any

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{secrets.rnd_N83YDqNsk1GzZB38mrvFK0d566PW}}
        run: |
           curl -X POST "https://api.render.com/v1/services/srv-d20ui4be5dus7388tpc0/deploys" \
               -H "Authorization: Bearer $rnd_N83YDqNsk1GzZB38mrvFK0d566PW" \
               -H "Content-Type: application/json" \
               -d '{}'
